name=StingRay MS5837 Library
version=1.0.0
author=StingRay
sentence=Updated original library to work with Wire2 of teensy v4.1
paragraph=A simple and easy library for the MS5837 pressure/depth sensor
category=Sensors
url=https://github.com/bluerobotics/BlueRobotics_MS5837_Library
architectures=*
